---
# ロケール事前確認
- name: Check locale
  ansible.builtin.command:
    cmd: localectl status
  register: check_localectl_result
  check_mode: false
  changed_when: false
  when: ansible_facts['os_family'] == "RedHat"

# ロケール設定
- name: Set locale
  ansible.builtin.command:
    cmd: localectl set-locale LANG=ja_JP.utf8
  when: "'LANG=ja_JP.utf8' not in check_localectl_result.stdout"

# タイムゾーン設定
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

# パッケージアップデート
- name: Yum updade
  ansible.builtin.yum:
    name: "*"
    state: present

# パッケージインストール
- name: Yum install
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - golang
      - cronie

# docker-composeのインストール
- name: Yum install docker-ce
  ansible.builtin.yum:
    name: docker
    state: present

# dockerサービスの起動
- name: Start & enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

# docker-composeのインストール
- name: Docker-compose2.32.4のインストール（バージョンは固定している）
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-Linux-x86_64"
    dest: "/usr/bin/docker-compose"
    mode: "u+x,g+x,o+x"
  become: true

# アプリをgit clone
- name: Git clone
  ansible.builtin.git:
    repo: https://github.com/sankaku/docker_rec_radiko.git
    dest: /home/ec2-user/docker_rec_radiko


# dockerコンテナのbuild
# （ansibleのdockerコマンドをインストールできないのでshellモジュールで代替する）
- name: Docker build docker_rec_radiko
  ansible.builtin.shell:
    cmd: 'docker build . -t docker_rec_radiko'
    chdir: /home/ec2-user/docker_rec_radiko
  register: result_shell
  args:
    creates: /home/ec2-user/docker_rec_radiko/Dockerfile


- name: Output shell resutl
  ansible.builtin.debug:
    msg: "{{ result_shell }}"

# cron設定　ここでは例として毎日17:55からTBSのラジオ番組を録音するようにしている
# cron確認は’sudo crontab -l’のようにsudoをつけて確認すること
- name: Cron setting
  ansible.builtin.cron:
    name: After6Junction
    minute: '55'
    hour: "17"
    job: '/home/ec2-user/docker_rec_radiko/radiko_docker_run.sh TBS 190 /home/ec2-user/docker_rec_radiko/ After6Junction'
    state: present
