---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update apt cache (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install httpd (Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
      ignore_errors: true