---
# This is httpd install playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: "Block of checks"
      block:
        - name: "Httpdパッケージの存在を確認する"
          ansible.builtin.package_facts:
            manager: auto
          register: result_rpm

        - name: "Check if apache2 is installed"
          ansible.builtin.assert:
            that:
              - "'apache2' in ansible_facts.packages"
            fail_msg: "Apache2 is not installed"

        - name: "Check if apache2 process exists"
          ansible.builtin.shell: "ps -ef | grep apache2 | grep -v grep || echo 'apache2 not running'"
          register: result_proc
          changed_when: false
          failed_when: false

        - name: "Httpdサービスが自動起動になっているかを確認する"
          ansible.builtin.systemd:
            name: httpd
            enabled: true
          register: result_enabled
          failed_when: result_enabled.state != 'enabled'

    - name: "結果をまとめて確認する"
      ansible.builtin.assert:
        that: "{{ result.failed == false }}"
      loop:
        - "{{ result_rpm }}"
        - "{{ result_proc }}"
        - "{{ result_enabled }}"
      loop_control:
        loop_var: result