---
# 各種情報の出力
- name: Information
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "hostname"
    - "uname -a"
    - "docker --version"
    - "docker-compose --version"
    - "yum list installed"
  register: result
  changed_when: false

- name: Output information
  ansible.builtin.debug:
    var: "result.results[item].stdout_lines"
  loop: "{{ range(0, 5) | list }}"
