on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint
      - name: Install Ansible collections
        run: ansible-galaxy collection install community.general
      - name: Run ansible-lint
        run: ansible-lint --force-color
        continue-on-error: true
