---
name: Molecule CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install molecule[docker] molecule-plugins[docker] ansible-core
        pip install docker

    - name: Install Ansible collections
      run: |
        ansible-galaxy collection install community.docker
        ansible-galaxy collection install community.general

    - name: Run Molecule tests
      run: |
        cd ansible-ec2
        molecule test
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint ansible-core

    - name: Install Ansible collections
      run: |
        ansible-galaxy collection install community.general

    - name: Run ansible-lint
      run: |
        cd ansible-ec2
        ansible-lint --force-color
      continue-on-error: true  # ansible-lintエラーでもCIを止めない

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-core

    - name: Run security scan with ansible-playbook --check
      run: |
        cd ansible-ec2
        ansible-playbook --check --diff site.yml -i hosts
      continue-on-error: true